name: Flutter CI

on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:    
      - '**'
  
jobs:
  build:
    name: Test, build debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '12.x'
          distribution: 'zulu' # See 'Supported distributions' for available options
          cache: 'gradle'
          check-latest: true

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.3'
          cache: true

      # Get flutter dependencies.
      - name: Download pub dependencies
        run: flutter pub get
    
      # Statically analyze the Dart code for any errors.
      - name: Run analyzer
        run: flutter analyze .

      # Run widget tests for our flutter project.
      # - name: Run tests
      #   run: flutter test

      # Build apk.
      - name: Build debug apk
        run: flutter build apk --debug --target-platform=android-arm64
      
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: debug-apk
      #     path: build/app/outputs/apk/debug/app-debug.apk